# Generated by Django 4.0.2 on 2022-02-26 20:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField()),
                ('structure_type', models.CharField(blank=True, max_length=125, null=True)),
                ('owned_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ownedproperty')),
            ],
        ),
        migrations.CreateModel(
            name='Locks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=125, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('room', models.CharField(blank=True, max_length=125, null=True)),
                ('lock_type', models.CharField(blank=True, max_length=256, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=125, null=True)),
                ('key_marking', models.CharField(max_length=50)),
                ('key_image', models.ImageField(null=True, upload_to='properties/keys/<built-in function id>')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.structure')),
            ],
        ),
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Full name')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('owned_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ownedproperty')),
            ],
        ),
    ]
