# Generated by Django 4.0.3 on 2022-03-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_ownedproperty_owner_alter_locks_key_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locks',
            name='key_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/keys/'),
        ),
        migrations.AlterField(
            model_name='locks',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='assets.structure'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='owned_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='assets.ownedproperty'),
        ),
    ]
